-- Primeiro, vamos criar uma categoria padrão para os relógios KAJIM
INSERT INTO categories (id, name, description, image_url, is_featured, sort_order) 
VALUES (
  gen_random_uuid(),
  'Relógios KAJIM',
  'Coleção premium de relógios KAJIM com design elegante e tecnologia avançada',
  '/watches-collection.jpg',
  true,
  1
) ON CONFLICT DO NOTHING;

-- Agora vamos inserir os produtos
INSERT INTO products (
  id,
  name,
  brand,
  model,
  price,
  description,
  image_url,
  images,
  movement,
  case_size,
  material,
  water_resistance,
  warranty,
  features,
  badges,
  custom_tags,
  stock_status,
  stock_quantity,
  is_visible,
  is_featured,
  status,
  category_id
) VALUES 
(
  gen_random_uuid(),
  'KAJIM Elite',
  'KAJIM',
  'Elite',
  2899.00,
  'Relógio de luxo com movimento automático e design elegante.',
  '/hero-watch.jpg',
  ARRAY['/hero-watch.jpg', '/watch-details.jpg', '/watches-collection.jpg'],
  'Automático Suíço',
  '42mm',
  'Aço Inoxidável 316L',
  '100m',
  '2 anos',
  ARRAY[
    'Movimento automático de alta precisão',
    'Cristal de safira resistente a riscos',
    'Pulseira em aço inoxidável premium',
    'Resistente à água até 100 metros',
    'Garantia internacional de 2 anos'
  ],
  ARRAY['Novo', 'Destaque'],
  ARRAY['luxo', 'automatico', 'premium'],
  'in_stock',
  15,
  true,
  true,
  'active',
  (SELECT id FROM categories WHERE name = 'Relógios KAJIM' LIMIT 1)
),
(
  gen_random_uuid(),
  'KAJIM Classic',
  'KAJIM',
  'Classic',
  1899.00,
  'Design clássico atemporal com acabamento refinado.',
  '/watch-details.jpg',
  ARRAY['/watch-details.jpg', '/hero-watch.jpg', '/watches-collection.jpg'],
  'Quartzo Suíço',
  '40mm',
  'Aço Inoxidável',
  '50m',
  '2 anos',
  ARRAY[
    'Movimento quartzo de alta precisão',
    'Design clássico e elegante',
    'Pulseira em couro premium',
    'Resistente à água',
    'Embalagem premium inclusa'
  ],
  ARRAY['Clássico'],
  ARRAY['classico', 'elegante', 'couro'],
  'in_stock',
  8,
  true,
  false,
  'active',
  (SELECT id FROM categories WHERE name = 'Relógios KAJIM' LIMIT 1)
),
(
  gen_random_uuid(),
  'KAJIM Sport',
  'KAJIM',
  'Sport',
  3499.00,
  'Performance esportiva com tecnologia avançada.',
  '/watches-collection.jpg',
  ARRAY['/watches-collection.jpg', '/hero-watch.jpg', '/watch-details.jpg'],
  'Cronógrafo Automático',
  '44mm',
  'Titânio',
  '200m',
  '3 anos',
  ARRAY[
    'Cronógrafo de alta performance',
    'Caixa em titânio ultra-leve',
    'Resistência extrema à água',
    'Pulseira esportiva premium',
    'Certificação ISO para mergulho'
  ],
  ARRAY['Sport', 'Limitado'],
  ARRAY['esportivo', 'titanio', 'cronografo', 'mergulho'],
  'in_stock',
  5,
  true,
  true,
  'active',
  (SELECT id FROM categories WHERE name = 'Relógios KAJIM' LIMIT 1)
);