// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhzrqjlyaqxdjfnxuhht.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5oenJxamx5YXF4ZGpmbnh1aGh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMTY1NzAsImV4cCI6MjA2OTU5MjU3MH0.cSFGa8lyhVHM0EuI-D9w1WfZFKasVx2S5ufIgNLw9wE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});